# 开发配置-公司环境
logging:
  config: classpath:conf/logback-dev.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
    shutdown:
      enabled: true
server:
  port: 8885
  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
spring:
  servlet:
    multipart:
      max-file-size: 500MB # 最大附件大小
      max-request-size: 500MB
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30
        min-idle: 0
  datasource:
    name: caas
    url: jdbc:mysql://127.0.0.1:3306/caas?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      max-active: 200
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictableIdle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.github.pettyfer.caas.framework.biz,com.github.pettyfer.caas.framework.system
  global-config:
    banner: false
    db-config:
      capital-mode: false
      id-type: ASSIGN_ID
      logic-delete-value: 'null'
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
kubernetes:
  client:
    master-url: ENC('7kfJ+Em3YOFKRkh5o4CMlYH08+BNNVZQc4xK0CLOh6lc3fHulm/xXBMrv1PJrOO9UYGU4CsZNLE=')
    token: ENC('02iLTr8wCpFebxvwbkHMSRFVHvBExrGtUh+cpQIvEsWAXQzU0oDG8HXRJT6DIFTEb7mUZOo3FkJNuWlvinXlJF4HklD6E2kwg7lI/u1b27Df/3YSV9onP4h89BFB7VQ1RzC8a1PUE5CfsqxKBkQOF9oCTTvtOOxYiN8T3vYPPo05XiOnmPvPdb+M3za231fVYHHJljl/LGA24HI29YUwa7jTT7scyz7+qmpspug3V7l69xbSnAvLpBC/kjtz0vCA2L2ErtTj1gCfB7cImHXuFmXkW6v0fJZ85BJJpmwgu1Qv1d489N2bPWpzPlBuGNO2cHvfAUuEV9SWZ8sm1BLZk/y76MYky1MkZgJ+cslob48mDWh7Lf9vLK2M38kKjTjc0rtmAUND1IG4ABiY9XgxTlC7HNEpXU44Y/wDDxsxMcG+wCkpXdZ3O9bVAKmH8fDIhW8S8j51acvM9HiyNVHahRs/3NZXTYTO0wKazTcqWC+eS/ngC529OMhVD/NBzNTuAKwg16xmLrqxbRJRsg3I2+UYsuISXVzZYrCVlkoFE2r4cIdusD6jK05VxZSUm04dO2NmyY4S/r44KbFwYb+eXvt6PtwpcR29B8e2ZFTinBS894WdywG9jejW3zO73HghixKXMtFg/oSyKjoK2qGW1/OaZt8HUOGqzaB5FN3BDzAoDRC0EOQm8gO1Qt1TMtSHnNLCwzDktjQRP09WNgEpikEEdCsi6qCxZXMFugGMUH2IPKUn7QEwrMDSBo0iaxvBKgA1J1E8l0L5zceo3wBu7/95nCCpv827EdHkNNsbquQio98Tw2wnCFIvNV8eHKBOyCVfSyzKPES3/rKL7inLFJzeRiQq20zIFxUcSTapWqc2Ns5tvkEIZjl57xqVzhSWSa1WvhZoaR/M/IlwmOsWotHWjin8qyfIoacAxynE9+YW2zbilc/FdS6zii5PPZZKWBisNPZU44R4ZncY7FT1VP99ic0t5Aggr+D6quFk8/83ADIat0PDxW+ZLz6CacGyVNSIv1h0/HjAcOtXObX8LmPOBgq+p1dFlIXP2HU1QtPNghfwgdvRKNTSaBB+8AVTPgr0VeB70uBIvtXshfirbDnxJAl2iJwadFs3cgDt64XEV3RSOvcU3UtzmEHXVYeUJsm9ttXaL03lz44moylevwVZlD3STlhSfJu6dBZgAR3vsmZPDy0sTUhDU2A+B2VtlTExZM5+TVJRI0DIqnFWCfQMCPqhX1ZW')
    cert-data: certs/ubuntu/ca.crt
  app-center:
    url: ENC('MsTC82LqhnB8lPFIDDdYwenbZTJtSyT+HOnGL4gLwkEXC5Cghq1nrw==')
    token: ENC('AjJISpt1vcqlkLhiriHsA9YUH4A8JutnCd5JoUuJZxHCTAoUsUg0AdiukCxmAznb1KxHW+uhe3KbF5CEvHfMbrHu5wnXAQMydUxWHPlU3A1ek0WIHiMIezgg+XAXsirv5wkgZAE5xwfa08bu1vJDg3oWPNo4VJg2kIwtizKYHLcIddglmHtdwh3WUjG1XMRXzgM0rlieX2blQbFPhqahNMaFHpiAZLBUImNNd63WFAYw/4AhGVqR1XWzuv8htEuYMt4aiupwIYGxXWSio30Gy9rSaHx2GjF0OwONdVGqID+EceocGjIZzaMUwEWiVYlqPP4SZAeeuPUG2ScNwQ0tSJHECBLPdIUJ7pDPsqyE3k1lvBGmXVyC88rsoqb4+jA7cvlXr9hnJeCwvuo+pP7IJdPqVwBDJlINm1QV219sj7w3nsRCJ0aOvir+V/9xMdD/57bMRU2ef4RDPLeDN3Qbzjh3rCGAaYN3WCP93eSFhbCVYThHN3+tMBoYo9VHzTp7aovIumzDKxv5a8qVHRQokPn4SVvVM0X5f11d/EJ77fsvCo0sl3Y++GasZdjeU7XWmmxXnUpHusUzM/cGKCYzrgVwSMAqffPyB9AY4wwXiEbP8aTU+xbVF6Kfacy9u5p/ZStxy5b2tv6gK7dstawskdpz3kgUab5YL7hKZzHCxxxsOn0a2qKuG+yvSyZ4/f+wqVA9HvtPL2oaOUM3SuG8LX/mSLSnEE3glPJZr4SVwubw/ikOsWpMPsIjCHwA16rIsyQTR/ul1zxwZkdLRL2RG5npUGfWRk+25/CEz/hkXsqybCbCJkjMrTNv5P9Vf1Y+pp8zyfuYOdk9n75rCcUWNX3LT9ex6JHM0otjEqRPODM473wdg6huRdO0vK7K8Cb6CpMSvufNbtHYLNOkILWz6jLtIH7W819SEYaaijN0qPMxEyErsktHjb6CyLoz2xSzbEkCLyKoDGV4J46tu5P8bhL2ARGZqx9a3wFScoyWaYuOCw+UtO5tmq+ViBKZM8d2I736+CEmCZq47KDrj6IX+dKEhPijPnsva3i35jWSafBzwt+S93xry6AmRV4FZOZZqpe6Jem4rU9qPlhjboSHiyzjF9jI08K8QGnnxzoDlwN2pG1K9vnDki0KAp04sRG1GtwYc4iRkcPA2GKuA9h37hB0FhplKLt9vWX6JppG3mJPag3Z3EsrCyZaPkd9MqsAXd6hog/0lOr+8mwzJvXcdxIlOlAuvVxqsztAhtgS09bL3tjo3y4OUg==')
attachment:
  local:
    name: user-center-local
    root: D:\\attachment\\
build:
  images:
    svn-pull: 192.168.0.4/tools/build-subversion-tool:1.0.0
    git-pull: 192.168.0.4/tools/build-git-tool:1.0.0
    sql-build: 192.168.0.4/tools/build-sql-tool:1.0.0
    persistence: 192.168.0.4/tools/build-persistence-tool:1.0.0
    maven-build: 192.168.0.4/tools/build-maven-tool:1.0.0
    nodejs-build: 192.168.0.4/tools/build-nodejs-tool:1.0.0
    docker-build: 192.168.0.4/tools/build-docker-tool:1.0.0
    notification: 192.168.0.4/tools/build-notification-tool:1.0.0