spring:
  application:
    name: caas-platform
    group: caas
  profiles:
    active: dev-centos
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator